BOOTMAGIC_ENABLE = no
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = no
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
NKRO_ENABLE = no
BACKLIGHT_ENABLE = no
MIDI_ENABLE = no
AUDIO_ENABLE = no
UNICODE_ENABLE = no
BLUETOOTH_ENABLE = no
RGBLIGHT_ENABLE = no
API_SYSEX_ENABLE = no
AUTO_SHIFT_ENABLE = no
LEADER_ENABLE = no
SLEEP_LED_ENABLE = no

LAYOUTS = planck_mit
LAYOUTS_HAS_RGB = no

